---
# Playbook to create generic templates
# Variable are pulled from a file in ./var-files
#

- name: Ansible generic configs
  vars_files:
    - ~/.vars-aci-credentials.yml
    - "{{ varfile }}"
  hosts: "{{ aci_env }}"

  connection: local
  gather_facts: no

  vars:
    playbook_version: '1.0'
    static_ports1: []
    static_ports2: []

  tasks:
  #
  # Compare playbook_version and input_vars_version
  #
  - name: 'Check input_vars_version' 
    fail: msg="playbook_version and input_vars_version do not match. Maybe you used the wrong template file?"
    when: playbook_version != input_vars_version

  #
  # Prepare SRX config file
  #
  - name: Prepare SRX config file
    template:
      src: jinja-templates/srx/srx-create-context.j2
      dest: ../data-classic-env/output-files/srx-create-context-{{general.fw}}-{{gv_srx.ri_prefix+srx.ri_id}}.txt
    no_log: true

# This is the end, my friend
...
